insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Ford', 'Silverado', 'LMS884');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Toyota', 'Camry', 'QDX089');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Chevrolet', '3 Series', 'AGG815');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'BMW', 'Civic', 'TXN416');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Ford', 'Mustang', 'VUP327');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camioneta', 'Ford', '3 Series', 'KYU332');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Honda', '3 Series', 'DTH480');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camioneta', 'Chevrolet', 'Silverado', 'QNR516');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Toyota', 'Civic', 'JJF134');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Honda', 'Camry', 'KBD611');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'BMW', 'Silverado', 'AXJ369');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Honda', 'Silverado', 'ZRF717');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Ford', 'Camry', 'ZLX250');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'BMW', '3 Series', 'JFW313');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Toyota', 'Camry', 'YYX103');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Honda', '3 Series', 'STB246');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'BMW', '3 Series', 'LHK033');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camioneta', 'Ford', 'Camry', 'VSN584');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camioneta', 'Honda', 'Civic', 'HQU310');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Toyota', '3 Series', 'FMM184');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Ford', 'Mustang', 'MUW993');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Toyota', 'Silverado', 'ZSH635');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Ford', 'Camry', 'YWY215');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'BMW', 'Civic', 'LCS272');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'BMW', 'Mustang', 'KRB705');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'BMW', 'Civic', 'KYO484');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Honda', 'Civic', 'JIK211');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Honda', '3 Series', 'FCH397');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Ford', 'Camry', 'DTY414');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camioneta', 'Ford', 'Civic', 'SCD138');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Ford', 'Camry', 'PRO121');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camioneta', 'Ford', 'Camry', 'EXR980');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'BMW', 'Civic', 'SCP076');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Chevrolet', 'Silverado', 'MEB275');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Honda', 'Civic', 'UKZ091');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Honda', '3 Series', 'IUL233');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Toyota', 'Camry', 'SVU189');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Chevrolet', 'Camry', 'WNW438');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Toyota', '3 Series', 'HDQ706');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'BMW', '3 Series', 'JRN952');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Ford', 'Camry', 'OXA889');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Chevrolet', 'Camry', 'NTW919');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Chevrolet', 'Silverado', 'IZQ964');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Honda', 'Camry', 'DVV551');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Honda', '3 Series', 'AZH780');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'BMW', 'Mustang', 'APY122');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Ford', 'Silverado', 'VON868');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('SUV', 'Toyota', 'Civic', 'IQL873');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Automovil', 'Toyota', 'Silverado', 'SJV391');
insert into Vehiculos (Tipo, Marca, Modelo, Patente) values ('Camion', 'Honda', 'Silverado', 'XWV537');
