//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_tr() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Resources.lang_tr", typeof(lang_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uygulama dilini seçmediniz!.
        /// </summary>
        internal static string LOC_AppLanguageNotSelected {
            get {
                return ResourceManager.GetString("LOC_AppLanguageNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a İptal.
        /// </summary>
        internal static string LOC_Cancel {
            get {
                return ResourceManager.GetString("LOC_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artır.
        /// </summary>
        internal static string LOC_Increase {
            get {
                return ResourceManager.GetString("LOC_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamam.
        /// </summary>
        internal static string LOC_Okay {
            get {
                return ResourceManager.GetString("LOC_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yenile.
        /// </summary>
        internal static string LOC_Refresh {
            get {
                return ResourceManager.GetString("LOC_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kalan gün sayısı: {0} - Lütfen {1} dikkatli olunuz..
        /// </summary>
        internal static string LOC_RemainingDays {
            get {
                return ResourceManager.GetString("LOC_RemainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kaydet.
        /// </summary>
        internal static string LOC_Save {
            get {
                return ResourceManager.GetString("LOC_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UI objelerine default text&apos;lerini atamak ister misiniz?.
        /// </summary>
        internal static string LOC_UpdateUIObjectsText {
            get {
                return ResourceManager.GetString("LOC_UpdateUIObjectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uyarı.
        /// </summary>
        internal static string LOC_Warning {
            get {
                return ResourceManager.GetString("LOC_Warning", resourceCulture);
            }
        }
    }
}
