USE [master]
GO
/****** Object:  Database [UCEMA]    Script Date: 23/03/2023 10:17:45 a. m. ******/
CREATE DATABASE [UCEMA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Empresa', FILENAME = N'C:\Documents\AP6\Database\UCEMA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Empresa_log', FILENAME = N'C:\Documents\AP6\Database\UCEMA_log.ldf' , SIZE = 504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [UCEMA] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UCEMA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UCEMA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UCEMA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UCEMA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UCEMA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UCEMA] SET ARITHABORT OFF 
GO
ALTER DATABASE [UCEMA] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [UCEMA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UCEMA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UCEMA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UCEMA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UCEMA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UCEMA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UCEMA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UCEMA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UCEMA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UCEMA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UCEMA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UCEMA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UCEMA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UCEMA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UCEMA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UCEMA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UCEMA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [UCEMA] SET  MULTI_USER 
GO
ALTER DATABASE [UCEMA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UCEMA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UCEMA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UCEMA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UCEMA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UCEMA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [UCEMA] SET QUERY_STORE = OFF
GO
USE [UCEMA]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 23/03/2023 10:17:45 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[ClienteId] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](25) NOT NULL,
	[FechaAlta] [datetime] NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[ClienteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Telefono]    Script Date: 23/03/2023 10:17:45 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Telefono](
	[TelefonoId] [int] IDENTITY(1,1) NOT NULL,
	[ClienteId] [int] NOT NULL,
	[Numero] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_Telefono] PRIMARY KEY CLUSTERED 
(
	[TelefonoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Cliente] ON 
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (1, N'Gerardo Tordoya', CAST(N'2023-03-06T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (2, N'Elena Valdéz', CAST(N'2017-12-23T00:00:00.000' AS DateTime), 0)
GO
INSERT [dbo].[Cliente] ([ClienteId], [Nombre], [FechaAlta], [Activo]) VALUES (3, N'Rodolfo Tordoya', CAST(N'1943-06-26T00:00:00.000' AS DateTime), 1)
GO
SET IDENTITY_INSERT [dbo].[Cliente] OFF
GO
SET IDENTITY_INSERT [dbo].[Telefono] ON 
GO
INSERT [dbo].[Telefono] ([TelefonoId], [ClienteId], [Numero]) VALUES (1, 1, N'3885843652')
GO
INSERT [dbo].[Telefono] ([TelefonoId], [ClienteId], [Numero]) VALUES (2, 1, N'4237800')
GO
INSERT [dbo].[Telefono] ([TelefonoId], [ClienteId], [Numero]) VALUES (3, 3, N'4255221')
GO
SET IDENTITY_INSERT [dbo].[Telefono] OFF
GO
ALTER TABLE [dbo].[Telefono]  WITH CHECK ADD  CONSTRAINT [FK_Telefono_Cliente] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([ClienteId])
GO
ALTER TABLE [dbo].[Telefono] CHECK CONSTRAINT [FK_Telefono_Cliente]
GO
USE [master]
GO
ALTER DATABASE [UCEMA] SET  READ_WRITE 
GO
