@startuml Sistema de Captura y Factura de Publicidad Editorial

' =========================================================================
' Author:       Gerardo Tordoya
' Create date:  2023-03-30
' Update date:  2023-04-02
' Description:  Arquitectura 7UP (basada en la Arquitectura Cardacci V2015)
' =========================================================================


' --- CONFIGURACION DEL DIAGRAMA -----------------------------------------------

skinparam linetype ortho
!theme plain


' --- TITULO DEL DIAGRAMA ------------------------------------------------------

title Arquitectura 7UP


' --- ENTIDADES ----------------------------------------------------------------

[View]

[Presenter]

[Model]

[Logic]

[Mapper]

[DataAccess]

[Abstract]

database "Database" {
}


' --- RELACIONES ---------------------------------------------------------------

Model <- Presenter
Model <- Logic
Model <- Mapper

View      -[dashed]-> Abstract
Presenter -[dashed]-> Abstract
Logic     -[dashed]-> Abstract
Mapper    -[dashed]-> Abstract
Model     -[dashed]-> Abstract

View      -[bold]> Presenter
Presenter -[bold]> Logic
Logic     -[bold]> Mapper
Mapper    -[bold]> DataAccess

DataAccess -[bold]-> Database


' --- PIE DE DIAGRAMA ----------------------------------------------------------

caption Copyright © 2023 Gerardo Tordoya


@enduml